name: Pytest

on:
  push:
    branches: [ "automated"]
  pull_request: 
    branches: ["main"]
  workflow_dispatch:

jobs:
  test: 
  run-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-pythin@v4
      with: 
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Unit Tests
      run: |
      python -m pytest -m unit

    - name: Integration Tests
      run: |
      python -m pytest -m integration